name: Test build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=https://github.com/gdamjan/nixpkgs/archive/refs/heads/make-portable.tar.gz

    - run: nix-build

    - name: Prepare artifacts
      run: |
        cp result/wallabag_*.raw ./
        sh -c 'sha256sum $0 > $0.sha256' wallabag_*.raw

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        retention-days: 5
        path: |
          wallabag_*.raw
          wallabag_*.raw.sha256

    - name: Create a github release from tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: |
          wallabag_*.raw
          wallabag_*.raw.sha256
