name: Make a release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11

    - run: nix-build --arg withSystemd false

    - name: Prepare release files
      run: |
        cp result wallabag_${GITHUB_REF#refs/tags/}.raw
        sha256sum wallabag_${GITHUB_REF#refs/tags/}.raw > wallabag_${GITHUB_REF#refs/tags/}.raw.sha256

    - name: Create a github release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: wallabag_*.raw*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
